# docker-compose.yml
services:
  mysql_single:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysql_single
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      TZ: UTC
    
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${MASTER_PORT}:3306"
    healthcheck:
      test: ["CMD", "sh", "-c", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s

volumes:
  mysql_data: